spring:
  application:
    name: monewping
  sql.init.mode: always
  profiles:
    default: ${SPRING_PROFILES_ACTIVE:dev}

  # DB 접속 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/monewpingdb
    username: monewping
    password: monewping
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

info:
  app:
    name: Heartsping
  java:
    version: ${java.version}
  spring-boot:
    version: 3.4.4
  datasource:
    url: ${spring.datasource.url}
    driver: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.properties.hibernate.ddl-auto}

server:
  port: ${PORT:8080}
  address: 0.0.0.0

naver:
  api:
    client-id: ${NAVER_CLIENT_ID:test-client-id}
    client-secret: ${NAVER_CLIENT_SECRET:test-client-secret}

