spring:
  application:
    name: monewping
  sql.init.mode: always
  profiles:
    active: default

  devtools:
    restart:
      # 기본 제외 패턴 유지하고 추가로 mapper 클래스 제외
      additional-exclude: "**/mapper/**/*MapperImpl.class"
      log-condition-evaluation-delta: true

  # DB 접속 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/monewpingdb
    username: monewping
    password: monewping
    driver-class-name: org.postgresql.Driver
    default_schema: monewping

  # JPA 설정
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Batch 설정
  batch:
    jdbc:
      initialize-schema: always

logging:
  file:
    path: ./logs
    name: monewping
  level:
    org.project.monewping: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

info:
  app:
    name: Heartsping
  java:
    version: ${java.version}
  spring-boot:
    version: 3.4.4
  datasource:
    url: ${spring.datasource.url}
    driver: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.properties.hibernate.ddl-auto}

server:
  port: ${PORT:8080}
  address: 0.0.0.0

naver:
  api:
    client-id: ${NAVER_CLIENT_ID:test-client-id}
    client-secret: ${NAVER_CLIENT_SECRET:test-client-secret}

# aws (추후 운영환경 분리)
aws:
  access-key: ${AWS_ACCESS_KEY:fakeAccessKey}
  secret-key: ${AWS_SECRET_KEY:fakeSecretKey}
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    backup:
      bucketName: ${AWS_BACKUP_BUCKET:monewping-backup-bucket} # 백업 전용 버킷명 (운영환경 분리 시 다르게 설정 가능)
      base-directory: ${AWS_BACKUP_BASE_DIR:backup/articles} # 백업 데이터 저장 기본 경로
      enabled: true
    logs:
      bucket-name: ${AWS_S3_LOGS_BUCKET:monewping-logs-storage} # 로그 파일을 넣는 버킷
      prefix: ${AWS_S3_LOGS_PREFIX:application-logs}
      enabled: false # 현재 aws 연동하지 않았기 때문에 false, 이후 연동 시 true 변경
